name: semantic-release

on: [push]

jobs:
  semantic-release:
    
    runs-on: ubuntu-latest

    container:
      image: node:16.15-alpine

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: apk add git  && npm ci

    - name: Launch semantic for service
      run: for moduleName in service logging-index; do cd ${moduleName} && npx semantic-release -e semantic-release-monorepo && cd ..; done;
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



